<?xml version="1.0" encoding="utf-8"?><Database Name="CisfExternalTraining" Class="TrainingDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=cisf12;Initial Catalog=CisfExternalTraining;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CisfExternalTrainingConnectionString" Provider="System.Data.SqlClient" />
</Database>